{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: nginx-tls

data:
  tls.crt: {{ .Values.tlssecrets.certificate | b64enc | quote }}
  tls.key: {{ .Values.tlssecrets.key | b64enc | quote }}
{{- end }}
