replicaCount: 1

#1.0
image:
  repository: nginx
  pullPolicy: IfNotPresent

#1.3
volumes:
  - name: test-nginx
    persistentVolumeClaim:
      claimName: test-nginx

volumeMounts:
  - name: test-nginx
  #Path to mount on the container itself
    mountPath: /disk-volume

#1.1, 1.2, 1.6, 1.7
service:
  type: LoadBalancer
  port: 8080
  targetPort: 80

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth 
  #tls
  tls:
    - secretName: nginx-tls
      hosts:
      - nginxlocal.com
  hosts:
    - host: nginxlocal.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: test-nginx
            servicePort: 8080


#1.5
resources:
   limits:
     cpu: "250m"
     memory: "500Mi"

authorization:
  user: <username>
  password: <password> 
  
tlssecrets: 
  certificate: "<certificate>"
  key: "<key>"
